### ISSUE TITLE
[FEAT] Dark mode without JS

### ISSUE THREAD

**Issue by iacore** [hearchco/frontend#382]
**Describe the bug**
Without Javascript, the page is 
ouch my eyes
system color scheme is dark
i expect the page to be dark

**To Reproduce**

1. Firefox
2. Disable Javascript
3. go to https://hearch.co/
4. Open developer tools, Inspector, Rules, click the "moon" icon

**Expected behavior**
The page should turn dark.

**Screenshots**
![image](https://github.com/user-attachments/assets/a7e15387-923d-4be1-9ec5-e426aebabc27)

**What's your setup? (please complete the following information):**
https://hearch.co/

**Additional context**
I think the default should be to use system color scheme with CSS.

At the very least, put this at the top of the site's CSS file:

```
:root {
  color-scheme: light dark;
}
```

**Comment by aleksasiriski** [comment]
Hey IA, nice to meet you :)

The problem I encountered was with TailwindCSS, as it allows either "system" theme to dictate the styling or a "selector/class" mode which allows switching the theme with JS, I couldn't find a solution to:
1) When JS is not available, use system theme
2) When JS is available, have the ability to change the theme

Adding the provided config looks to me oddly similar to [this]() head tag, which when used broke the look of the theme. I could try to fiddle with this again, as I want the same behavior as you do.

If you have any suggestings on how this can be properly achieved either with plain TailwindCSS or pure CSS working with TW, I would be very thankful.

**Comment by iacore** [comment]
```
body {
  color-scheme: light dark;
}
body.light {
  color-scheme: only light;
}
body.dark {
  color-scheme: only dark;
}
@media (prefers-color-scheme: light) {

}
@media (prefers-color-scheme: dark) {

}
```

**Comment by aleksasiriski** [comment]
I tried it but as I've already stated, TailwindCSS uses class mode to allow JS to switch the theme which means that @media in CSS does nothing. With this [PR](https://github.com/hearchco/frontend/pull/387) I've made the default theme dark at least, until we find the right solution (maybe 2 CSS files, one for noJS and other for JS users).

**Comment by aleksasiriski** [comment]
Also to explain, previously we only used media queries in CSS like you're proposing, but we got reports from users wanting to change to dark theme even though they have the system theme as light (and they want to keep it that way). That is the reasoning for doing themes with JS instead of just following the system theme using pure CSS. Even though we want to support as much functionality as possible w/o JS, this is what makes the larger group of users satisfied.

I think the proper way to support both would to generate 2 css files, one for nonJS users using media queries and the second which gets replaced by JS for the JS users (same as the currently generated CSS file). Idk how this would be implemented but I think it's doable, sadly I don't have the time to do it these days so if anyone finds this comment and wants to try it you're more than welcome to contribute.
